platform :ios, '10.0'

target 'NetworkLayerSwift_Example' do
  inherit! :search_paths
  pod 'NetworkLayerSwift', :path => '../'

  target 'NetworkLayerSwift_Tests' do
    inherit! :search_paths

    
  end
end
